services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: daysheets
      POSTGRES_USER: daysheets
      POSTGRES_PASSWORD: daysheets
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    environment:
      DB_NAME: daysheets
      DB_USER: daysheets
      DB_PASSWORD: daysheets
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

#   nginx-daysheets:
#     image: nginx:alpine
#     ports:
#       - "8443:443"
#       - "8082:80"
#     volumes:
#       - ./nginx/disposable-api.conf:/etc/nginx/conf.d/default.conf:ro
#       - /etc/letsencrypt:/etc/letsencrypt:ro
#     depends_on:
#       - backend

volumes:
  pgdata:
